### PR TITLE
Allow faulty values

### PR DESCRIPTION
**Pull request by karimbeyrouti**
This was causing issues with latest version of node

### CODE REVIEW

**Comment by bendrucker** [comment]
We discussed this in #53 and did the exact opposite of this change, originally motivated by #51. In order to change it again we'd need a failing test that this fixes.

**Comment by karimbeyrouti** [comment]
Interesting - It was failing with https://github.com/mllrsohn/node-webkit-builder - that was the fix to get the task to compile again. The error:

node_modules/node-webkit-builder/node_modules/graceful-ncp/node_modules/proxyquire/lib/proxyquire.js:13
    if (!mdl[key])  mdl[key] = original[key];
                             ^
TypeError: Cannot assign to read only property 'F_OK' of #<Object>

This error only started showing up when I upgraded to Node v.0.12.2 ( I had 0.10.36. before ) .
Would you like me to make a repo to reproduce that error. ( you will need latest version of Node ) ?

Thank you for your time.

**Comment by bendrucker** [comment]
Repo is fine, a failing test we can merge would be even better. CI is running on 0.12 and io and I run io locally but can try 0.12 as well. 

Here's the part of fs that was originally causing problems:

https://github.com/iojs/io.js/blob/178741637693a95f9e81200b486df2e6aee06986/lib/fs.js#L172-L176

Those lines are identical in Node master. 

The issue there was that some values were 0 and proxyquire was incorrectly trying to overwrite them. That was originally fixed by checking for `typeof mdl[key] === 'undefined'` in 16f66f3f811cd615b8a1ff520a89e3fee6bad8db and later changed to a a more correct `in` check in 37cc59a78325bc70ecd8a8bd88425d6b2ee5add5.

**Comment by karimbeyrouti** [comment]
Just installed IOJS ( v1.8.1 ) and had the same issue. 

You are going to laugh (or cry) - however I am not 100% certain what proxyquire does - only that it has started complaining with nodewebkit-builder . The crappy test I was going to do - is make a repo with the builder to show it breaking. Which is very very far from a unit test.

**Comment by bendrucker** [comment]
@adam-lynch can you help pin this down

**Comment by bendrucker** [comment]
I can't get a test to fail so I'm out of answers unless someone else can weigh in

99a155aa5e37bfbb815dd3ee5b0fc52d821029e3

**Comment by adam-lynch** [comment]
Uggghhhhh this again. I haven't a clue :/

**Comment by bendrucker** [comment]
Hang on -- @karimbeyrouti in your stack trace (https://github.com/thlorenz/proxyquire/pull/60#issuecomment-97830413) you've clearly got a pre-1.4 version of proxyquire. This is just #197 which @adam-lynch did his part in fixing.

`npm update` and open a new issue if this persists

**Comment by karimbeyrouti** [comment]
Yep, 

npm update alongside a match most recent version for nw builder ("node-webkit-builder":"^1.0.8")  fixed the issue. 

Thank you for your time !

**Pull request closed without merging**
