### PR TITLE
Added requireStubs() feature

### PR DESCRIPTION
**Pull request by samuelms1**
- Updated README with instructions
- Bumped version to 2.2.0

### CODE REVIEW

**Comment by samuelms1** [comment]
I've compared with #225 a little further and found that the use cases are actually different.  I thought they were the same initially, but #225 doesn't require that all modules be registered it just errors if a path to a module is not found rather than let things continue, so these are different.

**Comment by bendrucker** [comment]
Hmm. For something like avoiding network calls or spawning processes or intervals there are existing solutions: mocking `net`, `child_process`, `setInterval`, etc. globally. 

I'm pretty skeptical that this is a good idea to use. Your implementation seems good, I appreciate the up front effort. If you can provide other examples I'd reconsider.

**Comment by dbunna** [comment]
+1 for this change.

@bendrucker This PR is something I've wanted to see out of proxyquire for a long time. When writing unit tests, I want to verify that I have accounted for all dependencies of the unit under test and not accidentally let one through so I can test in complete isolation. I'm confused as to why it wouldn't be considered as a useful and important change.

**Comment by bendrucker** [comment]
Hi, that doesn't make the case for the feature, it just restates what the feature does. I'm still wondering why you'd need to mock _all_ dependencies. I'm not just looking out for your expressed need, but also what we're encouraging users to do. 

I see this as an anti-pattern that encourages boilerplate and makes simple dependencies unnecessarily hard to use. On first glance I'd be disinclined to use it in projects I work on. I'm looking to be convinced otherwise before we'd entertain this feature as submitted. I'm especially interested in how this feature overlaps with overriding global behavior like `net` as a means of preventing tests from breaking out of their intended, isolated behavior.

**Comment by ronelliott** [comment]
@bendrucker to be fair, you're not stating why you feel it's an anti pattern. This feature helps teach newer programmers how to properly mock a module under test and ensure they have them all. Please don't hold this project hostage to your own personal opinions.

**Comment by bendrucker** [comment]
I am interested in #225 and will work on finishing it up soon. I am going to decline this and keep the normal `require` behavior for any un-stubbed modules. I understand some of the problems you referenced but there are other Node tools that already suit those needs, [as mentioned above](https://github.com/thlorenz/proxyquire/pull/228#issuecomment-446290581):

* Open handles keeping a process open: https://github.com/mafintosh/why-is-node-running
* HTTP client requests: https://github.com/nock/nock

**Pull request closed without merging**
